### ISSUE TITLE
Flat products set to "One product per file" file handling are set to OnePerPage

### ISSUE THREAD

**Issue by matthewkayy** [tilialabs/tilia-phoenix-connect#10]
When tilia Phoenix Connect creates a new flat product with "One product per file" file handling it gets defaulted to OnePerPage and is never set back to OnePerFile:
https://github.com/tilialabs/tilia-phoenix-connect/blob/52cadcdadc703afd2fbba4c46763ae91b57ad897/source.js#L1279

**Comment by matthewkayy** [comment]
Created pull request to fix this issue: [Fix 'One product per file' page handling #11](https://github.com/tilialabs/tilia-phoenix-connect/pull/11)

**Comment by tiliadavid** [comment]
Merged in pull request
