### ISSUE TITLE
'products' element not found while parsing XML report

### ISSUE THREAD

**Issue by matthewkayy** [tilialabs/tilia-phoenix-connect#12]
tilia Phoenix Connect will log a warning to the messages in Direct mode for every job for "'products' element not found while parsing XML report"

It will also log an error and send Input Files to the "On error" connection for "Product 'XXXX.pdf' could not be placed in a layout, sending to Phoenix error"

This is due to the new v2 XML reports using a `products2` node instead of `products`

To resolve this line 860 needs to be updated to:
```
var items = childElement(doc.getDocumentElement(), "products2");
```

https://github.com/tilialabs/tilia-phoenix-connect/blob/52cadcdadc703afd2fbba4c46763ae91b57ad897/source.js#L860

**Comment by matthewkayy** [comment]
Raised a pull request to fix this: https://github.com/tilialabs/tilia-phoenix-connect/pull/13

**Comment by tiliadavid** [comment]
Merged in fix for script looking for old v1 products element
