### ISSUE TITLE
Which branch is the available tilia Phoenix Connect 

### ISSUE THREAD

**Issue by pkleinheider** [tilialabs/tilia-phoenix-connect#36]
Hi David,

at vividads, I keep getting this error message:

Dynamic property 'SelectedSheets' has invalid value 'Corflute/5 mm/2450 × 1230mm Long'

However, when I check the code inside the function `isPropertyValid` there is no catch for this property and a value of `true` gets returned.

Is the code of the App different from this repo?

best
Peter

**Comment by tiliadavid** [comment]
@pkleinheider - I'm investigating this issue via the Tilia Labs Help Desk. The User should follow up with you afterwards directly.

The main branch should be the exact same code as the latest version on the Enfocus App Store
