### ISSUE TITLE
Use JSON.parse() instead of eval()

### ISSUE THREAD

**Issue by dwightkelly** [tilialabs/tilia-phoenix-connect#4]
I recommend using JSON.parse() instead of eval().

**Comment by tilialabs** [comment]
Hi Dwight! Thanks for the suggestion.  

This JSON parsing and writing code was originally developed in the Phoenix configurator for Switch 2013 which didn't have JSON.parse().  We are looking into making this change soon though now that we are requiring Switch 2017 and above. 
 Using JSON.parse() is safer and addresses an outstanding issue with parsing larger response payloads.

**Comment by tilialabs** [comment]
We changed JSON parsing in version 3 to check for the existence of JSON.parse and use that function when available.  Marking this issue as closed.  Thanks again for the feedback Dwight.
