### ISSUE TITLE
Existing metadata is not copied to new job

### ISSUE THREAD

**Issue by dwightkelly** [tilialabs/tilia-phoenix-connect#6]
When Connect creates a new job @:
https://github.com/tilialabs/tilia-phoenix-connect/blob/6f4ec26000dfa6c7b58f8a102a11045cbb134497/source.js#L795

it is not copying the existing metadata from the input job. This metadata includes private data and datasets.

**Comment by tilialabs** [comment]
Hi Dwight,

Thanks for submitting this issue.  We understand what you're suggesting, but would like to learn more about the use case and urgency if possible.  Also, is this causing problems for any of your customers?

For CSV Import mode there is only a single input file so metadata copying might make more sense.  In direct mode, the input artwork file that triggers work to be done can be fairly random, so copying existing metadata might be less intuitive and/or useful.

**Comment by dwightkelly** [comment]
yes, we have a couple of customers that are complaining about missing metadata after processing jobs thru Tilia Phoenix element. Both private data and datasets.

**Comment by tiliadavid** [comment]
@dwightkelly Sorry for the delay on this! After just checking, we do pass through both private data and datasets. 

If you're having any issues with this, please reach out to us at support.tilialabs.com.
